version: "3.8"

networks:
  frontend_network:
  backend_network:
  db_network:


services:

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - db_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8881:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8880:8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - frontend_network
      - backend_network
      - db_network
