# The initial Virtual Machine provides the version of python is 3.8.10, so here I use 3.8-alpine
FROM python:3.9-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN apk add python3-dev build-base linux-headers pcre-dev \
    && pip install --upgrade pip \
    && pip install --no-cache-dir django psycopg2-binary \
    && pip install uwsgi \
    && pip install django-cors-headers

COPY . /code/
